import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tinyclrSidebar: [
    'getting-started',
    {
      type: 'category',
      label: 'SITCore Hardware',
      link: {type: 'doc', id: 'hardware'},
      collapsed: true,
      items: [
        'soc',
        'som',
        'sbc',
        'dev',
      ],
    },
    {
      type: 'category',
      label: 'Features',
      link: {type: 'doc', id: 'features'},
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Productivity Enhancements',
          collapsed: true,
          items: [
            'feature/debugging',
            'feature/memory',
            'feature/external-memory',
            'feature/unmanaged-heap',
            'feature/nuget',
            'feature/device-info',
          ],
        },
        {
          type: 'category',
          label: 'Modern OS Features',
          collapsed: true,
          items: [
            'feature/multithreading',
            'feature/reflection',
            'feature/collections',
            'feature/serialization',
            'feature/encoding-decoding',
            'feature/application-domain',
            'feature/marshal',
            'feature/regex',
            'feature/stream',
          ],
        },
        {
          type: 'category',
          label: 'Multimedia',
          collapsed: true,
          items: [
            'feature/graphics',
            'feature/touch-screen',
            'feature/user-interface',
            'feature/displays',
            'feature/image-decoders',
            'feature/font-support',
            'feature/camera',
            'feature/mjpeg-video',
            'feature/audio-playback',
            'feature/vnc',
          ],
        },
        {
          type: 'category',
          label: 'Networking Protocols',
          collapsed: true,
          items: [
            'feature/networking-core',
            'feature/http-https',
            'feature/mqtt',
            'feature/ppp',
            'feature/ethernet-ip',
          ],
        },
        {
          type: 'category',
          label: 'Networking Interfaces',
          collapsed: true,
          items: [
            'feature/wifi',
            'feature/ethernet',
            'feature/cellular',
          ],
        },
        {
          type: 'category',
          label: 'Cloud Support',
          collapsed: true,
          items: [
            'feature/azure',
            'feature/aws',
            'feature/google-cloud',
            'feature/ifttt',
            'feature/adafruit-io',
          ],
        },
        {
          type: 'category',
          label: 'Application Security',
          collapsed: true,
          items: [
            'feature/ip-protection',
            'feature/in-field-update',
            'feature/secure-storage',
            'feature/secure-boot',
          ],
        },
        {
          type: 'category',
          label: 'Data Security',
          collapsed: true,
          items: [
            'feature/tls',
            'feature/tls-client',
            'feature/tls-server',
            'feature/cryptography',
            'feature/hashing',
            'feature/password',
          ],
        },
        {
          type: 'category',
          label: 'Additional Features',
          collapsed: true,
          items: [
            'feature/usb-pc-comm',
            'feature/sqlite-database',
            'feature/file-system',
            'feature/sd-cards',
            'feature/power-management',
            'feature/watchdog-timer',
            'feature/real-time-clock',
            'feature/timers',
            'feature/resources',
            'feature/specialized',
          ],
        },
        {
          type: 'category',
          label: 'Pin Level Control',
          collapsed: true,
          items: [
            'feature/gpio',
            'feature/pwm',
            'feature/analog-in',
            'feature/analog-out',
            'feature/signal-control',
          ],
        },
        {
          type: 'category',
          label: 'Data Buses',
          collapsed: true,
          items: [
            'feature/spi',
            'feature/i2c',
            'feature/uart',
            'feature/usb',
            'feature/usb-client',
            'feature/usb-host',
            'feature/can',
            'feature/modbus',
            'feature/1-wire',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Configuration',
      link: {type: 'doc', id: 'configuration'},
      collapsed: true,
      items: [
        'special-pins',
        'bootloader',
        'tinyclr-config',
      ],
    },
    'downloads',
    'release-notes',
    'resources',
    'limitations',
  ],
};

export default sidebars;
